# Generated by Django 4.1.7 on 2023-03-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0002_alter_generatetype_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatetype',
            name='prompt',
            field=models.CharField(blank=True, max_length=350),
        ),
        migrations.AlterField(
            model_name='generatetype',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
