# Generated by Django 4.1.7 on 2023-03-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0005_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.CharField(blank=True, max_length=3000),
        ),
    ]
