# Generated by Django 4.1.7 on 2023-03-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0007_alter_recipe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatetype',
            name='imgPath',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='imgPath',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
