# Generated by Django 4.1.7 on 2023-03-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0008_alter_generatetype_imgpath_alter_recipe_imgpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AlterField(
            model_name='generatetype',
            name='imgPath',
            field=models.URLField(blank=True, max_length=800),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='imgPath',
            field=models.URLField(blank=True, max_length=800),
        ),
    ]
