# Generated by Django 4.1.7 on 2023-03-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0009_remove_recipe_name_alter_generatetype_imgpath_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
