# Generated by Django 4.1.7 on 2023-03-14 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0013_alter_recipe_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('imgPrompt', models.CharField(blank=True, max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 14, 11, 52, 46, 566131, tzinfo=datetime.timezone.utc)),
        ),
    ]
