# Generated by Django 4.1.7 on 2023-03-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0014_imagetype_alter_recipe_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
