# Generated by Django 4.1.7 on 2023-03-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0015_alter_recipe_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imgType',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
