# Generated by Django 4.1.7 on 2023-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0016_recipe_imgtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeType',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
