# Generated by Django 4.1.7 on 2023-03-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainInterface', '0017_alter_recipe_recipetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='persists',
            field=models.BooleanField(default=False),
        ),
    ]
